[package]

	name = "jp-router-common"
	version = "0.1.0"
	edition = "2021"

[dependencies]

	arcstr = { version = "*", features = [ "serde" ] }
	chrono = { version = "*", features = [ "serde" ] }
	serde = { version = "*", features = [ "derive" ] }
